### ISSUE TITLE
Some redundancy data in serialize/deserialize

### ISSUE THREAD

**Issue by Rouen007** [InteractiveComputerGraphics/Discregrid#10]
i found that m_cell_map and m_cells never change after initialization in cubic_lagrange_discrete_grid.cpp and they only related to the size "m_n_cells". And why to save them in serialize/deserialize?

[Also, i want to ask is there any references which can help me to understand the serialize and deserialize operations? i do not know m_cell_map's and m_cells's functionality to cope with the interpolation.]

Thank you very much.

**Comment by JoseAntFer** [comment]
Hi,

m_cell_map changes every time a function is added to the interpolation grid and every time the .reduceField(...) method is called. It needs to be saved in the serialization because it is required to query the interpolation data structure. Essentially, it maps the global cell index with the reduced cell index set (obviously this only makes sense if you use a reduction for the interpolation grid).

serialize/deserialize are common operations to write and read data from RAM to disk.

Best regards,
José.

**Comment by Rouen007** [comment]
> Hi,
> 
> m_cell_map changes every time a function is added to the interpolation grid and every time the .reduceField(...) method is called. It needs to be saved in the serialization because it is required to query the interpolation data structure. Essentially, it maps the global cell index with the reduced cell index set (obviously this only makes sense if you use a reduction for the interpolation grid).
> 
> serialize/deserialize are common operations to write and read data from RAM to disk.
> 
> Best regards,
> José.

Thank you very much.

At first, i thought reducefield API only related to Density maps. i will check the functionality of reducefield.

[Lately, i tried to use and understand the sdf formate data and the interpolation operation of "Discregrid". And found those im-compacted formates in serialization.]

Best Retgards,
Ang Lu
