### ISSUE TITLE
How can I use this in deformable-deformable collision detection?

### ISSUE THREAD

**Issue by FantasyVR** [InteractiveComputerGraphics/Discregrid#8]

**Comment by JoseAntFer** [comment]
Discregrid precomputes values from continuous function fields following a grid structure in order to provide very fast interpolation from those values later on. This implies that if the underlying field changes, the samples must be recomputed. If you want to use Discregrid for deformable collision detection via signed distance functions, you would need to recompute the sampled values every time step of your simulation, which would hardly be more efficient than using explicit collision detection techniques. Not to mention the difficulties of detecting self-collisions using only signed distance functions.

**Comment by FantasyVR** [comment]
@JoseAntFer In the paper, *An hp-adpative discretization algorithm for singed distance field generation*, it claims that **this collision handling method can be used for rigid body simulation, rigid-deformable and deformable-deformable simulation** (page 3, section 2: SDF-based collision detection).
In Addition, I wonder  which file contains the source code of  `hp-adaptive SDF cconstruction` algorithm? Or isn't this repository the implementation of the referenced papers?

If I want to detect the collision between deformable bodies, would you give me some advice?
